services:
    paybas.quicklogin.listener:
        class: paybas\quicklogin\event\listener
        arguments:
            - @config
            - @template
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }
